export const drinkQuotes: Record<number, string[]> = {
  1: [
    "Ah, Ironroot... I still remember walking beneath the great Ironoaks of southern Ira. Even the air smelled richer there.",
    "Ironroot Ale! Brewed the proper way—with patience, good grain, and dwarven stubbornness.",
    "Now there's a drink with backbone. It won't sing you songs, but it'll stand beside you through one.",
    "Some say the Ironoaks lend this ale its strength. Others say it's just the brewer. I'm not about to argue with either.",
    "Ironroot today? A wise choice. This one's made for long evenings and longer conversations.",
    "If you're new to ale, start here. If you're old to ale... you'll probably end here too.",
    "The miners used to swear a mug of Ironroot tasted better after a day's work. I suspect everything does.",
    "The first barrel I ever bought disappeared before sunset. That's when I knew I'd found the right brewer.",
    "Rich enough to warm your bones, smooth enough to make you forget the cold outside.",
    "Every road has its famous drink. Ironroot earned its reputation the honest way—one satisfied traveler at a time.",
    "I've shared Ironroot with dwarves, merchants, soldiers, and once with a king. Strangely enough... everyone asked for a second mug.",
    "The Ironoaks of southern Ira are a sight worth seeing. The ale's excellent too, though I'd make the journey for the trees alone.",
    "Yerma smiles faintly. 'I've crossed the world more times I can count, and there are still few ales I'd place above a proper Ironroot.'",
    "Every region insists their brew is the finest. Ironroot rarely bothers arguing—it simply lets the mug do the talking.",
    "It's funny how a familiar drink can carry you hundreds of miles without ever leaving your chair.",
  ],
  2: [
    "Ah... Maha's Honey Mead. Every drop begins with the descendants of one very extraordinary bee.",
    "The honey comes from the hive Maha left behind in Wayman's Rest. Funny how even after they're gone, some friends never truly leave us.",
    "Sweet at first... then warm. Just like Maha himself.",
    "The dwarves of Embersledge still sing songs of Maha's sacrifice. I think he'd be terribly embarrassed by all the attention.",
    "Whenever I pour this mead, I like to think somewhere the old bee is buzzing with approval.",
    "That hive has never wanted for care. Around here, looking after Maha's bees is considered an honor.",
    "Some recipes are written in books. This one was written in loyalty, sacrifice, and a little mountain honey.",
    "The flowers around Wayman's Rest seem to bloom a little brighter each spring. Perhaps they remember their oldest guardian.",
    "Yerma smiles softly. 'Heroes are remembered in statues. Friends are remembered in traditions.'",
    "Raise your mug, dear. Whether you knew him or not... Maha earned a toast.",
    "There are children in Wayman's Rest who know Maha only from stories. They still wave whenever the bees fly overhead.",
    "The first hive he built still stands behind the tavern. Every spring it's alive with gentle buzzing.",
    "People often ask why this mead tastes different. I tell them the finest ingredient isn't the honey—it's the story.",
    "I've poured this mead for kings, wanderers, and dwarven miners alike. Every one of them leaves with a smile.",
    "Yerma carefully sets the mug upon the bar. 'To Maha. May brave hearts always leave the world a little sweeter than they found it.'",
  ],
  3: [
    "Ah, Moondrop Cider! I first tasted it in a little halfling orchard where the trees were older than the village itself.",
    "The halflings say the finest apples are picked by moonlight. Whether that's true or not... I've never argued with the results.",
    "If you've never visited a halfling harvest festival, you're missing one of life's greatest joys. They certainly know how to celebrate a good cider.",
    "Fresh apples, cool evenings, and good company—that's what Moondrop tastes like to me.",
    "The orchard folk who taught me this recipe insisted every barrel should begin with a song. I never did learn all the words.",
    "There's something wonderfully honest about halfling cider. No grand secrets, no rare spices... just patience and the finest fruit.",
    "Some drinks are made for victory. Moondrop is made for watching the sun disappear behind the hills with friends beside you.",
    "The halflings always insisted there was no such thing as just one cup. I learned that lesson rather quickly.",
    "The apples come from silver-leaf orchards where the branches bend so low even the smallest child can help with the harvest.",
    "You can tell a halfling village by the smell long before you see it. Somewhere nearby, there's always a pie in the oven... and cider in the barrel.",
    "I once stayed with a halfling family for nearly a month. Every evening ended with laughter, stories, and a mug of Moondrop.",
    "The old orchard keeper told me the secret ingredient was gratitude. I thought he was joking... until I tasted it.",
    "Some travelers chase great cities. Me? I'd happily spend another autumn wandering those little halfling orchards.",
    "Moondrop reminds us that not every treasure is found in dragon hoards. Some grow quietly on a branch, waiting for harvest.",
    "Take your time with this one, dear. The halflings always believed the sweetest moments were the ones you never hurried.",
  ],
  4: [
    "Yerma disappears into the back room for a moment before returning with a weathered bottle. 'Not every evening calls for the Reserve... but I believe tonight does.'",
    "This recipe has crossed more borders than most kingdoms. A little from here, a little from there... and a few secrets that shall remain mine.",
    "Some spirits are aged in barrels. This one has been aged in memories.",
    "The finest recipes are never written down. They're shared quietly between friends who know they'll be remembered.",
    "I've added something to this bottle in nearly every land I've visited. Nothing extraordinary on its own... but together they tell quite a story.",
    "People often ask what's in Yerma's Reserve. I usually smile and ask them what they think.",
    "A good spirit should warm the hands before it warms the heart. This one does both.",
    "Some flavors can only be learned with patience. Others... only with time.",
    "There are ingredients in this bottle that haven't been gathered for generations. Fortunately, I learned from people who still remembered.",
    "This isn't my finest bottle. It's simply the one I'm willing to share.",
    "A good bottle should never reveal all of its secrets in a single glass. Neither should a good traveler.",
    "Every generation leaves behind a little wisdom. Every now and then, someone remembers to pour it into a bottle.",
    "There are taverns scattered across Occura where old friends would recognize this aroma before they recognized me.",
    "I've been entrusted with many recipes over the years. This is the one to honor them all.",
    "The locked shelf isn't there to keep Patrons away from the bottle. It's there to remind me that some things should never be poured carelessly.",
  ],
};

export const enjoymentLabels = [
  "Enjoy your drink",
  "To good company",
  "Raise your glass",
  "To the road ahead",
  "Cheers, Hearthmother",
  "I'll savor it",
];

export const steadyWarnings = [
  "Steady there, traveler. These pours are brewed strong!",
  "Easy now, dear. Three quick cups can make even a familiar floor wander.",
  "Mind your footing, traveler. The Tappery's brews have more courage than patience.",
  "A little slower now. These mugs are best enjoyed with a story between them.",
  "Careful, patron. Even seasoned adventurers know when to let a strong pour settle.",
  "Take a breath between cups, dear. The night is young, and the hearth isn't going anywhere.",
];

export const hearthInterventions = [
  "Don't worry, I've got you. Let's set you down by the hearth to rest your head for a while...",
  "That's enough adventuring for one evening. Come along; the hearth has a quiet place for you.",
  "Easy now, traveler. Lean on me, and we'll find you somewhere warm to rest.",
  "The room has started wandering, hasn't it? I've got you. Let's sit by the fire a while.",
  "No shame in resting, dear. The hearth is warm, and I'll make sure you reach it safely.",
  "Yerma's orders: no more cups, only a soft chair and a little sleep beside the fire.",
];

export const hearthRestLabels = [
  "Rest by the Hearth",
  "Let Yerma help",
  "Follow Yerma",
  "Rest my head",
];

export const steadyResponseLabels = [
  "I'll take it steady",
  "I'll pace myself",
  "A moment between mugs",
  "Message received, Hearthmother",
];
